spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/testcruddb
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testcruddb
    username: test
    password: test
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
