spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:unittestdb
    username: test
    password: test
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true